= SDK Manager
:icons: font

image:https://img.shields.io/github/go-mod/go-version/dev-itbasis-sdkm/sdkm[GitHub go.mod Go version]
image:https://codecov.io/github/dev-itbasis-sdkm/sdkm/graph/badge.svg?token=OQB80UGOBE[link=https://codecov.io/github/dev-itbasis-sdkm/sdkm]

== Links

* link:TODO.adoc[TODO]

* link:CHANGELOG.adoc[ChangeLog]

== Install

. Unpack to any directory.
For example, in `$HOME/.sdkm/` (further this path in the documentation will be referred to as
`SDKM_HOME`)
. (Optional) Add the path to `$SDKM_HOME` to `PATH` - if you use hooks, this will be done automatically: `export PATH=${SDKM_HOME}:${PATH}`
. Unpack scripts for shims: `./sdkm reshim`
. Enjoy icon:smile-o[]

== Terminal hooks

. ZSH
+
It is necessary to add the line `source $SDKM_HOME/hook.zsh` to `~/.zshrc`

. Bash
+
It is necessary to add the line `source $SDKM_HOME/hook.bash` to `~/.bashrc`

== SDK installation location

By default, the `${HOME}/sdk` directory is used.

You can set the path via the `SDKM_SDK_ROOT_DIR` environment variable or via the `--sdk-root-dir` argument on the command line (takes precedence over the environment variable)

== Caching available versions

To optimize the number of requests, the application caches the list of received SDK versions in `$SDKM_HOME/.cache` for a day
