name: lint & diff

on:
  push:
  pull_request:

jobs:
  lint-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          check-latest: true

      - run: go run builder/main.go dependencies
      - run: go run builder/main.go lint

  lint-editorconfig:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: editorconfig-checker/action-editorconfig-checker@main
      - run: editorconfig-checker
