name: Tests

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
          check-latest: true

      - run: go run builder/main.go dependencies
      - run: go run builder/main.go generate
      - run: go run builder/main.go lint
      - run: go run builder/main.go unit-test

      - name: Test Summary
        uses: test-summary/action@v2
        with:
          paths: "junit-report.xml"
        if: always()

      - name: Upload test results to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/test-results-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: "junit-report.xml"
          verbose: true

      - name: Upload coverage reports to Codecov
        if: ${{ !cancelled() }}
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage-unit.out
          verbose: true
